version: "3"

services:

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #   ports:
  #     - "5432:5432"
  #


  web:
    build: .
    image: flask_app
    restart: always
    volumes:
      - .:/app
    environment:
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - PYTHONIOENCODING
      - FLASK_APP
      - APP_BASE_URL
      - LANG
      - APP_SECRET_KEY
    ports:
      - 8080:8080
    # depends_on:
    #   - db
